arrow cls tests
uccross/skyhookdm-ceph-cls pull request #73
Opened 2020-09-04 00:54 UTC by kingwind123

Now we need to create popper step for tests.

2020-09-04 01:29 UTC, ivotron requested changes

2020-09-04 01:29 UTC, ivotron commented on .popper.yml
> +    make VERBOSE=1
if we want to run tests, we can:
 1. bring back the micro-osd.sh
 2. boot a 1-node cluster and then run the tests.
 3. invoke the test binaries from here or run `make test`

2020-09-04 01:29 UTC, ivotron commented on src/cls_sdk_test.cc
> +//#include <rados/objclass.h>
these can be removed if they're not being used

2020-09-04 01:29 UTC, ivotron commented on src/test_utils.cc
> +// TOOD
we can also remove the to-do comment

2020-09-04 01:29 UTC, ivotron commented on src/test_utils.h
> +// destroy_one_pool_pp()
we can remove the comments

2020-09-04 01:29 UTC, ivotron commented on src/test_utils.cc
> +{
this has mixed 2- and 4-space indentation. maybe we can use clang-format or an alternative. Maybe in another issue

2020-09-04 01:32 UTC, ivotron commented on .popper.yml
> +    make VERBOSE=1
we can also do the above but as a separate step so that we can now which step is the one failing (build or tests)

2020-09-10 23:30 UTC, jlefevre commented on scripts/micro-osd.sh
> +mon_allow_pool_delete = true
this was added to enable pool deletion within method delete_one_pool_pp().

2020-09-10 23:31 UTC, jlefevre commented on src/cls_sdk.cc
> +  CLS_ERR("Look over here");
We can remove this please, and the next line can be changed to log level 20 instead of 0.

2020-09-10 23:31 UTC, jlefevre commented on src/cls_sdk_test.cc
> +  //std::string pool_name = "testPool";
can be removed please.

2020-09-10 23:32 UTC, jlefevre commented on src/cls_sdk_test.cc
> +  //std::string pool_name = "testPool2";
same

2020-09-10 23:34 UTC, jlefevre commented on src/cls_sdk_test.cc
> +  ASSERT_EQ(0, ioctx.exec("myobject", "arrow_cls", "test_coverage_write", in, out));
maybe a better name such as test_object, not critical though.

2020-09-10 23:36 UTC, jlefevre commented on src/test_utils.cc
> +std::string get_temp_pool_name(const std::string &prefix)
can you add a comment here to note from where in the ceph tree we copied these ceph functions?  just for reference, thanks.

2020-09-10 23:36 UTC, jlefevre commented on src/test_utils.h
> +
or comment for reference to ceph tree functions can go here instead, thanks.

2020-09-11 00:29 UTC, kingwind123 commented on scripts/micro-osd.sh
> +mon_allow_pool_delete = true
ok added comments

2020-09-11 19:28 UTC, jlefevre approved these changes
LGTM, thanks Xiongfeng!

2020-09-11 19:41 UTC, ivotron commented on src/CMakeLists.txt
> +add_library(cls_arrow_cls SHARED cls_sdk.cc)
since this is not the arrow class (yet), we could move it back to sdk, to avoid confusion

2020-09-11 21:00 UTC, jlefevre commented on .popper.yml
> +    cp build/lib/libcls_arrow_cls.so* /usr/lib64/rados-classes/
cls_sdk

2020-09-11 21:01 UTC, jlefevre commented on scripts/micro-osd.sh
> +osd class load list = lock log numops refcount replica_log statelog timeindex user version arrow_cls
cls_sdk

2020-09-11 21:01 UTC, jlefevre commented on src/CMakeLists.txt
> +set_target_properties(cls_arrow_cls PROPERTIES
cls_sdk

2020-09-11 21:02 UTC, jlefevre commented on src/CMakeLists.txt
> +install(TARGETS cls_arrow_cls DESTINATION ${cls_dir})
cls_sdk

2020-09-11 21:02 UTC, jlefevre commented on src/cls_sdk.cc
> +CLS_NAME(arrow_cls)
cls_sdk

2020-09-11 21:02 UTC, jlefevre commented on src/cls_sdk.cc
> +  cls_register("arrow_cls", &h_class);
cls_sdk

2020-09-11 21:03 UTC, jlefevre commented on src/cls_sdk_test.cc
> +  ASSERT_EQ(0, ioctx.exec("test_object", "arrow_cls", "test_coverage_write", in, out));
cls_sdk

2020-09-11 21:03 UTC, jlefevre commented on src/cls_sdk_test.cc
> +  ASSERT_EQ(0, ioctx.exec("test_object", "arrow_cls", "test_coverage_write", in, out));
cls_sdk

2020-09-11 21:07 UTC, jlefevre reviewed
class rename requires changes in several places, so i marked them for xs

2020-09-15 00:23 UTC, ivotron approved these changes

2020-09-15 00:25 UTC, merged